### ISSUE TITLE
Redesign Product Card Component

### ISSUE THREAD

**Issue by Nababratadeb-NITA** [Nababratadeb-NITA/Artism#11]
- hello there so I need someone to redesign my product card component now at this moment its looking very basic so I want you to make its attractive and user friendly

**Comment by ankitk26** [comment]
Hi @Nababratadeb-NITA, I can work on some designs and you can let me know if it suits you or if any changes are required. Can you assign me to this issue?

**Comment by Nababratadeb-NITA** [comment]
Yeah sure @ankitk26 can you show me some designs that you'll make 
Then I'll assign you

**Comment by ankitk26** [comment]
@Nababratadeb-NITA, I made some designs. Please let me know if any changes or new designs are required.

![pic1](https://user-images.githubusercontent.com/53444460/211988575-7d929289-f7cb-498a-946c-2acce02bb6e9.png)

**Comment by Nababratadeb-NITA** [comment]
@ankitk26 how can I see the examples

**Comment by Nababratadeb-NITA** [comment]
Ok @ankitk26  that 2nd one looks cool to me

**Comment by ankitk26** [comment]
Ok, I will start working on this. Can you assign me?

**Comment by Nababratadeb-NITA** [comment]
Ok @ankitk26  that 2nd one looks cool to me
Yeah sure I'm assigning you this work

**Comment by ankitk26** [comment]
@Nababratadeb-NITA, I changed the code for the product card. It looks like this now. I also added the onAdd() function to the "Add to Cart" button on the card.

![image](https://user-images.githubusercontent.com/53444460/212043394-cf5a8132-6e49-4dd1-82bb-9d19943ac57a.png)

**Comment by ankitk26** [comment]
Adding one more screenshot of the screen

![image](https://user-images.githubusercontent.com/53444460/212056235-05be1c2d-d961-4753-82e5-0d4144349808.png)

**Comment by Nababratadeb-NITA** [comment]
Great design 👍

**Comment by Nababratadeb-NITA** [comment]
hey @ankitk26  i have one mode request can you please redesign the product details page ?

**Comment by ankitk26** [comment]
I have redesigned the product detail page. Let me know if there are any changes to be done.

![image](https://user-images.githubusercontent.com/53444460/212257780-fafe70de-3d99-4b9a-b8a5-50e7d9d20b32.png)

**Comment by ankitk26** [comment]
Here is an alternative for the product description

![image](https://user-images.githubusercontent.com/53444460/212259470-a5cf6050-f474-41dc-9c50-d0a277790640.png)

**Comment by Nababratadeb-NITA** [comment]
And @ankitk26 where would be the picture

**Comment by ankitk26** [comment]
It is the same as the above image. I just changed the representation of the category

**Comment by Nababratadeb-NITA** [comment]
Okk do it @ankitk26
