### ISSUE TITLE
Can anyone redesign my product card ?

### ISSUE THREAD

**Issue by Nababratadeb-NITA** [Nababratadeb-NITA/Artism#23]
hello there i want someone who can redesign my product card and the banner as well

**Comment by Abhishek7Tech** [comment]
@Nababratadeb-NITA Hi I would like to work on the product card redesign.

**Comment by Nababratadeb-NITA** [comment]
@Abhishek7Tech  can you show me some samples

**Comment by Abhishek7Tech** [comment]
@Nababratadeb-NITA 
![Screenshot (107)](https://user-images.githubusercontent.com/93655183/216911166-c2f32f5d-e92e-44a5-84d4-93953f9dd909.png)
![Screenshot (3)](https://user-images.githubusercontent.com/93655183/216911209-9b274270-bba5-4441-92d2-fc3570ff50e3.png)
![Screenshot (51)](https://user-images.githubusercontent.com/93655183/216911470-5a86016f-1d2a-4c69-bb8f-708f720ec5a0.png)

**Comment by shyamtawli** [comment]
Hey @Nababratadeb-NITA can you share your design or any refrence?

**Comment by Nababratadeb-NITA** [comment]
``
