### ISSUE TITLE
Fix the download button in product details page

### ISSUE THREAD

**Issue by Nababratadeb-NITA** [Nababratadeb-NITA/Artism#24]
when i download any image in jpeg format it shows me file is corrupted can anyone please help me to fix this issue

**Comment by Abhishek7Tech** [comment]
@Nababratadeb-NITA Looks like your button isn't the issue here. The source of image is. 
Question. Where are you hosting the images?

**Comment by Nababratadeb-NITA** [comment]
@Abhishek7Tech in the sanity cms

**Comment by Abhishek7Tech** [comment]
@Nababratadeb-NITA try with different image format. It may work.

**Comment by Nababratadeb-NITA** [comment]
@Abhishek7Tech  still not working

**Comment by Abhishek7Tech** [comment]
@Nababratadeb-NITA  Can I have a look from where on your site a user can download images and where images are saved.

**Comment by Nababratadeb-NITA** [comment]
@Abhishek7Tech yes why not go to /pages/product/[id] file path

**Comment by Abhishek7Tech** [comment]
@Nababratadeb-NITA How to recreate the issue? I can't find the download button on your website?
