### ISSUE TITLE
Filtering is not working properly 

### ISSUE THREAD

**Issue by Nababratadeb-NITA** [Nababratadeb-NITA/Artism#6]
**Describe the bug**
I write the code for filtering product by its category in console its showing the filter product but in website its not working properly can you just find the bug and fix it

**To Reproduce**
1. Go to '../components/category.jsx'
3. Scroll down to line no 8

**Expected behavior**
it should show the filtered products on the screen

**Comment by Nababratadeb-NITA** [comment]
can anyone solve this please

**Comment by martinyis** [comment]
I can try to solve this bug, can you assign?

**Comment by Nababratadeb-NITA** [comment]
hey @martinyis  sorry for late replying 
Yeah sure you can try I will assign you the task if you reply yes

**Comment by martinyis** [comment]
> hey @martinyis  sorry for late replying 
> 
> Yeah sure you can try I will assign you the task if you reply yes

Yes

**Comment by martinyis** [comment]
I got lost in your files, I don't really understand where your Category component is used. But the problem is that when you run the filter function it doesn't send products back. So wherever your category component is located, you need to make a function there which will get a new products as soon as filter function is called

**Comment by Nababratadeb-NITA** [comment]
@martinyis you can find the file in this path "artism/components/category.jsx" and this file is linked with index.js file i mean all the products are fetched from index.js file 

Hope you understand now🤗

**Comment by Nababratadeb-NITA** [comment]
![IMG_20230110_113612.jpg](https://user-images.githubusercontent.com/116813147/211474409-ae850227-20eb-4286-8b82-11844574b72f.jpg)

![IMG_20230110_113528.jpg](https://user-images.githubusercontent.com/116813147/211474455-78b72f9a-9fd1-4f71-8da2-d1dcbd6447e8.jpg)

@martinyis

**Comment by Nababratadeb-NITA** [comment]
![IMG_20230110_113528.jpg](https://user-images.githubusercontent.com/116813147/211474552-00b4c6a8-2aea-4240-b44b-ca12e4d68521.jpg)
